=== 如何理解 Ruby 变量与常量

CAUTION: 本章节涉及较为进阶内容，建议第一次接触编程或缺乏编程经验的开发者暂时跳过这一章节。

**让人出乎意料的是：Ruby 并没有真正意义的常量**

这句话一出口，必然有人不服。「Ruby 里全大写的关键字，不就是常量吗？」此言差矣。虽然 Ruby 中的全大写的关键字会被作为常量来识别，但是 Ruby 中的常量本质上还是变量，因为你依然可以给常量任意赋值，只是会触发警告。

[source,ruby]
----
CONST_A = 'foo'
CONST_A = 'bar' # => warning: already initialized constant CONST_A
puts CONST_A # 'bar'
----

另一个常常被人混淆的概念则是 Ruby 中的 `Object#freeze` 方法。「把变量冻结后我就不能编辑了，这难道不是常量吗？」

[source,ruby]
----
a = 'foo'.freeze
a << 'bar' # FrozenError (can't modify frozen String: "a")
----

这同样不是常量，而是另一个名词「不变量（immutable）」。我们可以看下面的例子，只要不是编辑对象本身，我依然可以给冻结后的对象赋予一个完全的新值。

[source,ruby]
----
a = 'foo'.freeze
a = 'bar'
puts a # 'bar'
----

虽然可变量（mutable）、不变量（immutable）听起来和变量（variable）以及常量（const）听起来非常像，但它们是完全不一样的东西。我们要把数据的存储拆成两个部分来看，代号和内容。变量、常量说的是代号所指的对象的可变还是不可变；而可变量、不变量指的是指向的那个对象里面内容物的可变还是不可变。

我们举个例子，现在有一座房子，地址是 A，A 就是变量名。A 房子里住着小明。如果小明可以把这 A 房子卖给小王，那么这个 A 房子就是个「变量」；如果小明不被允许把 A 房子卖给其他人，那么 A 就是一个「常量」。A 房子里的小明体重 100 斤，今天小明吃成了 200 斤，那么他就是个「可变量」；如果小明住进房子里，所有性状不可能变化了，那么他就是个「不变量」。至于今天 A 房子里住着一个 100 斤的小明，我明天把 A 房子转给另一个 200 斤的小王住，那就不管「可变/不变」什么事，而是「变量/常量」的事情了。

简而言之，「可变/不变」是数据结构本身的特性，而「变量/常量」是指向数据的代号的特性。

讲到这里结论就已经很明显了：Ruby 没有常量，全大写的常量其实本质上还是变量只是会在改变时抛出 warning，而 freeze 是将可变量转换成不可变量。
